### ISSUE TITLE
Bidirectional 

### ISSUE THREAD

**Issue by runahue** [UzixLS/sdrsharp-catcontroller#1]
Hello friend
A lot of thanks for this great plugin
I am using sdrsharp like panadapter for my HF Transceiver 
This plugin is only one direction... sdrsharp is reading frequency from my radio but ... 
when I change frequency or mode on sdrsharp it doesn't send changes using cat
Is possible bidirectional?
Thanks a lot

**Comment by UzixLS** [comment]
Thanks for suggestion. I'll consider it in the near future.

**Comment by UzixLS** [comment]
@runahue, could you try this build?
[SDRSharp.SerialController.dll.zip](https://github.com/UzixLS/sdrsharp-catcontroller/files/684914/SDRSharp.SerialController.dll.zip)

**Comment by runahue** [comment]
It was tested and running really fine :-)
A lot of thank's.
