### ISSUE TITLE
Hamlib compatibility ?

### ISSUE THREAD

**Issue by bammi** [UzixLS/sdrsharp-catcontroller#3]
installed v1.5 of sdrsharp-catcontroller  in sdr-sharp r 1650  (v1.0.0.1650)
connected to one end of a pair VSPE (COM12-Com13)

works wonderfully with fldigi and rigCat configured with xml from here
http://www.w1hkj.com/xmls/kenwood/TS-50.xml

so I know my setup is good.
However,
with wsjtx v1.8 and Hamlib for cat control, with TS-50S selected as the rig type, baud rate set to 9600 data bits 8, 1 stop bit (doesn't have an option for parity, so I am assuming it is N), I am having no luck. Connection times out.
From the command line, running rigctl in interactive mode
rigctl-wsjtx -m 201 -r \\.\com13 -s 9600 -vvvvv

opens the serial port successfully (can see it in the verbose output due to the -vvvvv command line option)
issuing a 'f' command to rigctl, correctly send 3 chars "FA;"
then all subsequent read attempts fail:
   "Timed out 0.310637 seconds after 0 chars"   is the message
It re-tries several times.

Any advise, happy to help you debug, screen share if you like etc.

73 de kc1ccr
bammi
jbammi@mac.com

**Comment by UzixLS** [comment]
@bammi, could you try this build?
[SDRSharp.SerialController.dll.zip](https://github.com/UzixLS/sdrsharp-catcontroller/files/1764240/SDRSharp.SerialController.dll.zip)

**Comment by bammi** [comment]
Thanks Eugene,
That worked wonderfully! I’ll go to Github and see what you checked in.

appreciate your efforts and prompt response.

cheers,
bammi
